welcome.message: Welcome, bootRun user

# SPRING
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5060/templatedb
    username: templateapp
    password: t3mpl4t34pp
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    virtual-host: /
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2