name: gke

on:
  release:
    types: [created]

env:
  PROJECT_ID: ${{ secrets.GKE_CLUSTER }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: europe-west1-b
  DEPLOYMENT_NAME: template-app-deployment
  IMAGE: template-app 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: GCloud CLI setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_CLUSTER }}

      - name: Configure Docker to use GCloud CLI to authenticate
        run: gcloud --quiet auth configure-docker

      - name: Get the GKE cluster credentials
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build the image
        id: build_image
        env:
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$IMAGE_TAG" \
            .
          echo "::set-output name=IMAGE_PATH::gcr.io/$PROJECT_ID/$IMAGE:$IMAGE_TAG"

      - name: Push the image to Google Container Registry
        run: docker push ${{ steps.build_image.outputs.IMAGE_PATH }}

      - name: Set up Kustomize
        run: |-
          cd ~/k8s
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy to GCE
        env:
          IMAGE_PATH: ${{ steps.build_image.outputs.IMAGE_PATH }}
        run: |-
          cd ~/k8s
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=$IMAGE_PATH
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide